#!/usr/bin/env node
/**
 * Regenerates tool-specific agent rule files from AGENTS.md.
 * Usage: npm run rules:sync
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const agentsPath = path.join(root, "AGENTS.md");

const HEADER = `<!-- Generated by scripts/sync-rules.mjs from AGENTS.md — do not edit by hand. -->\n`;

const CURSOR_RULE_RE =
  /<!--\s*sync:cursor-rule\s+name="([^"]+)"\s+globs="([^"]+)"\s*-->([\s\S]*?)<!--\s*\/sync:cursor-rule\s*-->/g;

function stripCursorRuleMarkers(md) {
  return md
    .replace(CURSOR_RULE_RE, (_m, _name, _globs, body) => body.trim())
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

function extractCursorRules(md) {
  const rules = [];
  for (const match of md.matchAll(CURSOR_RULE_RE)) {
    rules.push({
      name: match[1],
      globs: match[2],
      body: match[3].trim(),
    });
  }
  return rules;
}

function ensureDir(filePath) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
}

function writeFile(rel, contents) {
  const abs = path.join(root, rel);
  ensureDir(abs);
  fs.writeFileSync(abs, contents, "utf8");
  console.log(`wrote ${rel}`);
}

function main() {
  if (!fs.existsSync(agentsPath)) {
    console.error("AGENTS.md not found at", agentsPath);
    process.exit(1);
  }

  const agents = fs.readFileSync(agentsPath, "utf8");
  const body = stripCursorRuleMarkers(agents);
  const cursorRules = extractCursorRules(agents);

  writeFile(
    ".cursor/rules/project.mdc",
    `---
description: Project conventions from AGENTS.md (source of truth)
alwaysApply: true
---

${HEADER}
${body}
`,
  );

  for (const rule of cursorRules) {
    writeFile(
      `.cursor/rules/${rule.name}.mdc`,
      `---
description: ${rule.name} (synced from AGENTS.md)
globs: ${rule.globs}
alwaysApply: false
---

${HEADER}
# ${rule.name}

${rule.body}
`,
    );
  }

  writeFile("CLAUDE.md", `${HEADER}\n${body}\n`);
  writeFile(".windsurfrules", `${HEADER}\n${body}\n`);
  writeFile("CONVENTIONS.md", `${HEADER}\n${body}\n`);
  writeFile(
    ".aider.conf.yml",
    `# Generated by scripts/sync-rules.mjs — do not edit by hand.\nread: CONVENTIONS.md\n`,
  );
  writeFile(".github/copilot-instructions.md", `${HEADER}\n${body}\n`);

  console.log("rules:sync complete");
}

main();
