import { APP_VERSION } from "@locations/api/version";
import { vi } from "vitest";
import { sessionUser } from "./api-app";

export { sessionUser };

export function createAdminOpsMock(overrides: Record<string, unknown> = {}) {
  return {
    getOpsOverview: vi.fn(async () => ({
      worker: "ok",
      db: true,
      flags: { signupDisabled: false, landingEnabled: true, globeEnabled: true, demoTour: true },
      users: { total: 1, byRole: { admin: 1 } },
      stuckImportCount: 0,
      entitledCount: 1,
      lapsedCount: 0,
      sampledAccounts: 1,
      attention: { stuckImportCount: 0, pastDueCount: 0, unverifiedCount: 0, adminCount: 1 },
      diagnostics: { stripeConfigured: false, resendConfigured: false, r2Configured: true, queueConfigured: false },
    })),
    listOpsUsers: vi.fn(async () => ({ users: [], cursor: null, limit: 25 })),
    getOpsUserCard: vi.fn(async () => ({
      id: "user-a",
      email: "a@example.com",
      name: "User A",
      role: "user",
      emailVerified: true,
      createdAt: "2026-01-01T00:00:00.000Z",
      visitCount: 0,
      sourceCount: 0,
      sessionCount: 0,
      lastSessionAt: null,
      billingStatus: "none",
      recapOptIn: false,
      latestImport: null,
      latestExport: null,
    })),
    setOpsUserRole: vi.fn(async () => ({ ok: true as const })),
    revokeOpsUserSessions: vi.fn(async () => ({ ok: true as const, revoked: 1 })),
    verifyOpsUser: vi.fn(async () => ({ ok: true as const })),
    wipeOpsUser: vi.fn(async () => ({ ok: true as const })),
    getOpsBilling: vi.fn(async () => ({ histogram: {}, pastDue: [], cursor: null })),
    getOpsImports: vi.fn(async () => ({ jobs: [], stuckCount: 0, cursor: null })),
    getOpsExports: vi.fn(async () => ({ jobs: [], byStatus: {}, cursor: null })),
    getOpsEmail: vi.fn(async () => ({ kinds: [], lastRecap: null, resendConfigured: false })),
    getOpsMaps: vi.fn(() => ({
      commercialTiles: false,
      osrmConfigured: false,
      geocodeConfigured: false,
      customHostsAllowlist: false,
      customHostCount: 0,
    })),
    getOpsDemo: vi.fn(async () => ({ exists: false })),
    getOpsAnalytics: vi.fn(async () => ({
      byRole: {},
      importsReady: 0,
      importsError: 0,
      recapOptIn: 0,
      unverifiedCount: 0,
      entitledCount: 0,
      lapsedCount: 0,
      sampledAccounts: 100,
      signupsByWeek: [],
    })),
    listOpsAudit: vi.fn(async () => ({ entries: [], cursor: null })),
    getOpsDiagnostics: vi.fn(async () => ({
      worker: true,
      db: true,
      flagsLoaded: true,
      version: APP_VERSION,
      stripeConfigured: false,
      resendConfigured: false,
      r2Configured: true,
      queueConfigured: false,
    })),
    patchOpsFlags: vi.fn(async () => ({ ok: true as const })),
    resetOpsFlag: vi.fn(async () => ({ ok: true as const })),
    inviteOpsUser: vi.fn(async () => ({ ok: true as const, id: "invited-1", reset: "skipped" as const })),
    sendOpsPasswordReset: vi.fn(async () => ({ ok: true as const, reset: "skipped" as const })),
    failOpsImportJob: vi.fn(async () => ({ ok: true as const })),
    failOpsExportJob: vi.fn(async () => ({ ok: true as const })),
    sendOpsEmailTest: vi.fn(async () => ({ ok: true as const, result: "skipped" as const })),
    getOpsMapsProbe: vi.fn(async () => ({
      probes: [
        { name: "tiles", ok: false, status: 0, ms: 0 },
        { name: "osrm", ok: false, status: 0, ms: 0 },
        { name: "geocode", ok: false, status: 0, ms: 0 },
      ],
    })),
    writeOpsAudit: vi.fn(async () => undefined),
    listToggleFlags: vi.fn(async () => ({
      flags: { signupDisabled: false, landingEnabled: true, globeEnabled: true, demoTour: true },
      overlay: {
        signup_disabled: null,
        landing_enabled: null,
        globe_enabled: null,
        demo_tour: null,
      },
      source: {
        signup_disabled: "env",
        landing_enabled: "env",
        globe_enabled: "env",
        demo_tour: "env",
      },
      meta: {
        signup_disabled: { updatedBy: null, updatedAt: null },
        landing_enabled: { updatedBy: null, updatedAt: null },
        globe_enabled: { updatedBy: null, updatedAt: null },
        demo_tour: { updatedBy: null, updatedAt: null },
      },
    })),
    ...overrides,
  };
}
